### ISSUE TITLE
Invalid request provided: Deprecated runtime version specified. 

### ISSUE THREAD

**Issue by mshiriv** [aws-samples/arc-zonal-shift-demo#3]
*What's the issue?*
While creating the stack, all canary logical resources failed by *CREATE_FAILED* status, which causes stack failure and rollback triggers. The following message as status reason shows in CloudFormation console:
`Resource handler returned message: "Invalid request provided: Deprecated runtime version specified. (Service: Synthetics, Status Code: 400, Request ID: 0383f09b-537a-4e5a-bc2c-82aee98eac51)" (RequestToken: aa4241c0-11e6-c1ed-2fd2-b29ef8621aae, HandlerErrorCode: InvalidRequest)`

*How to reproduce?*
Use the [readme](https://github.com/aws-samples/arc-zonal-shift-demo?tab=readme-ov-file#how-to-deploy-the-template) command.

**Comment by gavinmcc** [comment]
This is resolved now, thanks for the report!
